### ISSUE TITLE
Struct fields and enum names have changed in new devkitpro for switch

### ISSUE THREAD

**Issue by minkcv** [Cpasjuste/libcross2d#17]
I was able to find that `ENTRYTYPE_DIR` was changed to `FsDirEntryType::FsDirEntryType_Dir` and `fileSize` to `file_size` but I don't know about `entry_data`.

https://github.com/Cpasjuste/libcross2d/blob/5892c406443ca3ee77385988ce9217e7cb473550/source/platforms/posix/posix_io.cpp#L98

Also in `switch_sys.h`
`PcvModule_Cpu` became `PcvModule_CpuBus`
`PcvModule_Gpu` became `PcvModule_GPU`
`PcvModule_Emc` became `PcvModule_EMC`

**Comment by Cpasjuste** [comment]
Hi,

This have been fixed some time ago, closing!
