### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Cyan4973** [Cpasjuste/libcross2d#18]
I was trying to build `libcross2d`, as a dependency of `retrodream` actually,
but was unable to get it to build.

The selected building process starts by invoking `cmake`, generating a `Makefile`, and then running it with `make`.

It invariably fails with this message :  
```
In file included from ~/dev/dreamcast/retrodream/libcross2d/include/cross2d/c2d.h:23,
                 from ~/dev/dreamcast/retrodream/libcross2d/source/skeleton/audio.cpp:7:
~/dev/dreamcast/retrodream/libcross2d/include/cross2d/skeleton/config.h:10:10: fatal error: libconfig.h: No such file or directory
   10 | #include <libconfig.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/cross2d.dir/build.make:63: CMakeFiles/cross2d.dir/source/skeleton/audio.cpp.o] Error 1
```

Given that `libconfig.h` is present in `/include/cross2d/skeleton/libconfig`, I would assume a missing include path in the script, that may possibly be invisible for those who have `libcross2d` already installed on their host.

**Comment by Cyan4973** [comment]
Instructions provided in a separate repository

**Comment by minkcv** [comment]
Can you link the instructions? I have this issue.

**Comment by minkcv** [comment]
I found that 
    sudo apt install libconfig-dev

worked for me on an ubuntu system

**Comment by Cyan4973** [comment]
> libconfig-dev
worked for me on an ubuntu system

Yes, installing this dependency works for Linux compilation.

Strangely enough, the instructions to compile `libcross2d` are provided in a different repository : 
https://github.com/Cpasjuste/libcross2d-examples

Instructions are provided for 5 platforms, including Linux.

Dreamcast platform is not included however, such that trying to compile `libcross2d` for Dreamcast (which is a necessary requirement for [retrodream](https://github.com/Cpasjuste/retrodream)) isn't an obvious task.

**Comment by Cpasjuste** [comment]
Yep sorry, I'm very bad with readme and instructions. I didn't find the time yet to update all build instructions for each platform (this is a lot of work), and the Dreamcast one have a lot of work :/
