### ISSUE TITLE
Renderer transform applied twice

### ISSUE THREAD

**Issue by minkcv** [Cpasjuste/libcross2d#19]
I noticed that when I transform the renderer like so
```
renderer->setRotation(45);
```
It rotates 90 degrees. I think the transform is being applied twice in the renderer code. The renderer extends rectangle so the rectangle gets the rotation and then the renderer also applies this transform to children. 

https://github.com/Cpasjuste/libcross2d/blob/8c8d31b7ecb61a965b18fc2853ba7d8d389b797c/source/skeleton/renderer.cpp#L65

**Comment by Cpasjuste** [comment]
Hi @minkcv , thanks for the report! I guess I changed something, someday, and forget that.. I'll fix this tomorrow.

**Comment by Cpasjuste** [comment]
Hi again,

This have been fixed in 58108dbab0beb6410c3cbe04c0275ada0c0463e3

Thanks again  @minkcv

**Comment by minkcv** [comment]
👍
