### ISSUE TITLE
glad vs glew on Windows

### ISSUE THREAD

**Issue by minkcv** [Cpasjuste/libcross2d#20]
I had a build error on windows in libcross2d/source/platforms/gl2/gl_renderer.cpp where it was trying to do gladLoadGL() even though that is surrounded by 

    #if defined(__PLATFORM_LINUX__) || defined(__SWITCH__)

I had `-DPLATFORM_WINDOWS=ON`. I'm guessing the condition should have `PLATFORM_LINUX` without the double underbars.

**Comment by minkcv** [comment]
Removing double underbars didn't help. Still not sure on this one.

**Comment by Cpasjuste** [comment]
Yeah, I didn't test the windows build since I while. I hate to boot and windows, and there's a lot of hackery to make it work. 
I'll try to do that this weekend thought, or next week.

**Comment by minkcv** [comment]
Ok. Thanks. You will want to install this as well

    pacman -Sy mingw-w64-x86_64-libconfig

**Comment by minkcv** [comment]
I also had to remove `dl` from the C2D_LDFLAGS for the linux target in the libcross2d CMakeLists.txt

Then I was able to get it working 😄

**Comment by Cpasjuste** [comment]
Feel free to make a PR ?
